### ISSUE TITLE
Scores in books in lecterns not sorting by score

### ISSUE THREAD

**Issue by CarteBMO** [Plagiatus/Statistic-Books-MC#1]
![image](https://github.com/user-attachments/assets/f33cb6a4-fe9c-4088-94df-7529a0bc10a8)

**Comment by Plagiatus** [comment]
Thank you for the report.

Unfortunately, I cannot reproduce this issue in my testworld. Thus, to allow me to try to reproduce this issue, could you provide me with the following:

1. the `world/data/command_storage_sb.dat` file
2. the `scoreboard.dat` file from the same folder 
3. the tracked scoreboard name from the screenshot.
4. which version (of both MC and the pack) you're using, what server software does the server use (vanilla / sponge / forge etc)?
5. if possible whether there are any (related) errors in the console when you start the server / world.

Does it happen with all scoreboards you're tracking or only this specific one?

**Comment by CarteBMO** [comment]
3. It's all scoreboards actually, I have made lecterns out of all 75 of the
custom minecraft statistics and none of them are organized.

[image: image.png]

This screenshot though is sb.custom.open_chest

4. We were originally using Minecraft 1.21.1 and then I added the data pack
version 1.4
Once I saw the lecterns were not updating, I updated the server yesterday
to 1.21.3 and the data pack to 1.5.1 and the problem is still happening.
We run the server on vanilla but some of us use client-side forge mods like
optifine or minimap (I doubt that affects it since most of us do not use
them)


5. Upon loading the server, I get this stream of text, the first bits are
just loot table problems with some vanilla tweaks 1.21.3 stuff I believe.
[10:47:34 INFO]: Environment: Environment[sessionHost=
https://sessionserver.mojang.com, servicesHost=
https://api.minecraftservices.com, name=PROD]
[10:47:35 WARN]: Found loot table element validation problem in
{minecraft:loot_table/minecraft:entities/husk}.pools[2].entries[0]: Unknown
loot table called husks_drop_sand:entities/husk
[10:47:35 WARN]: Found loot table element validation problem in
{minecraft:loot_table/minecraft:entities/villager}.pools[2].entries[0]:
Unknown loot table called villager_death:entities/villager
[10:47:35 WARN]: Found loot table element validation problem in
{minecraft:loot_table/minecraft:entities/bat}.pools[2].entries[0]: Unknown
loot table called bat_membranes:entities/bat
[10:47:35 WARN]: Found loot table element validation problem in
{minecraft:loot_table/minecraft:entities/player}.pools[1].entries[0]:
Unknown loot table called graves:entities/player
[10:47:35 WARN]: Found loot table element validation problem in
{minecraft:loot_table/minecraft:entities/shulker}.pools[2].entries[0]:
Unknown loot table called double_shulker_shells:entities/shulker
[10:47:36 INFO]: Loaded 1337 recipes
[10:47:36 INFO]: Loaded 1471 advancements
[10:47:36 INFO]: Starting minecraft server version 1.21.3
[10:47:36 INFO]: Loading properties
[10:47:36 INFO]: Default game type: SURVIVAL
[10:47:36 INFO]: Generating keypair
[10:47:36 ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
at java.base/java.io.FileInputStream.readBytes(Native Method) ~[?:?]
at java.base/java.io.FileInputStream.read(FileInputStream.java:287) ~[?:?]
at
java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
~[?:?]
at
java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
~[?:?]
at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
~[?:?]
at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:329)
~[?:?]
at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:372)
~[?:?]
at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:215)
~[?:?]
at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:169) ~[?:?]
at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
~[?:?]
at java.base/java.io.BufferedReader.fill(BufferedReader.java:160) ~[?:?]
at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
~[?:?]
at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347) ~[?:?]
at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436) ~[?:?]
at aqy$1.run(SourceFile:102) [server-1.21.3.jar:?]
[10:47:36 INFO]: Starting Minecraft server on *:25565
[10:47:37 INFO]: Using default channel type
[10:47:37 INFO]: Preparing level "world"
[10:47:37 INFO]: Preparing start region for dimension minecraft:overworld
[10:47:38 INFO]: Preparing spawn area: 0%
[10:47:38 INFO]: Preparing spawn area: 0%
[10:47:38 INFO]: Preparing spawn area: 2%
[10:47:38 INFO]: Time elapsed: 1285 ms
[10:47:38 INFO]: Done (1.589s)! For help, type "help"


Finally,
Occasionally this pops up in the server log
[10:55:51 ERROR]: Tried to load invalid item: 'No key author in
MapLike[{pages:['{"extra":[{"bold":true,"text":"bigchuy9"},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"meibraham"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"CaptainCarte"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"McWifi78"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"Icekriegspaz"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"trenir"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""}],"text":""}']}];
No key title in
MapLike[{pages:['{"extra":[{"bold":true,"text":"bigchuy9"},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"meibraham"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"CaptainCarte"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"McWifi78"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"Icekriegspaz"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"trenir"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""}],"text":""}']}]
missed input:
{"minecraft:written_book_content":{pages:['{"extra":[{"bold":true,"text":"bigchuy9"},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"meibraham"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"CaptainCarte"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"McWifi78"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"Icekriegspaz"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"trenir"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""}],"text":""}']}};
No key id in
MapLike[{components:{"minecraft:written_book_content":{pages:['{"extra":[{"bold":true,"text":"bigchuy9"},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"meibraham"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"CaptainCarte"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"McWifi78"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"Icekriegspaz"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""},"\\n",{"extra":[{"bold":true,"text":"trenir"}],"text":""},"\\n",{"extra":[{"italic":true,"text":"0"}],"text":""}],"text":""}']}}}]'

I believe this is just when I have a book taken out of the lectern or
something because it is typically not popping up... this is one very long
line by the way.


Thank you so much for trying to help me!

**Comment by Plagiatus** [comment]
Thanks for the infos. You're right, client side mods should have no effect on this.

Is it possible for you to provide 1) and 2)? those would be the most crucial parts for me to figure out what's going on. The error message might help a little bit, but mainly 1) and to a lesser extend 2) would be essential to this riddle :)

**Comment by CarteBMO** [comment]
Yes I did attach them, they are just at the bottom of the email :)

**Comment by CarteBMO** [comment]
Here they are again, in case there was some email error

**Comment by Plagiatus** [comment]
Unfortunately github seems to be removing these attached files before they reach me (i also checked my emails, not just the github issue). Could you upload them directly to the issue on the website?

**Comment by CarteBMO** [comment]
[CMDs.zip](https://github.com/user-attachments/files/17966540/CMDs.zip)

**Comment by CarteBMO** [comment]
Alright, I just sent a zip file on the issues page, let me know if you can
find it!

**Comment by Plagiatus** [comment]
Alright, there we go.   
The issue seems to come from the fact that you chose refreshType 3 aka "Global Timer". I'm [specifically disabling the sorting for that one](https://github.com/Plagiatus/Statistic-Books-MC/blob/main/data/sb/function/update/all.mcfunction) in favor of a different, more performant approach... However, [that approach is apparently not implemented, it's just an empty file lol](https://github.com/Plagiatus/Statistic-Books-MC/blob/main/data/sb/function/update/sort_all.mcfunction).

So, for a quick fix while you wait for me to repair this issue, you can choose any other refresh method. Can I ask why you're using the probably most impactful one, especially since you have 70+ lecterns? :D I'd recommend using option 0, players won't know the difference and it's only run on-demand instead of sorting and modifying and storing everything every 5 minutes.

**Comment by CarteBMO** [comment]
I was trying every refresh type while I was playing with the settings, I must have left it on 3 by mistake. I will set it back to 0 and see if that works!

**Comment by CarteBMO** [comment]
That worked!
Do you have a venmo or some other way to show my appreciation, we are going to have so much fun with these stat books and you have been such a great help <3

**Comment by Plagiatus** [comment]
great to hear it!

I'm also looking into that error. It seems to only happen occasionally, but i can reproduce it thanks to your data. I'll be looking into what's going on there.

I do have a kofi (https://ko-fi.com/plagiatus) and PayPal (https://paypal.me/plagiatus), thank you so much, i appreciate that. 🥇

**Comment by Plagiatus** [comment]
I've published the fix for both of these issues (and one additional one) in [release 1.5.2](https://github.com/Plagiatus/Statistic-Books-MC/releases/tag/1.5.2). Thank you again for the report, and enjoy the statistics books :D
